global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerting_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # VideoAI Application
  - job_name: 'videoai-api'
    static_configs:
      - targets: ['host.docker.internal:8000']  # FastAPI metrics endpoint
    metrics_path: /metrics
    scrape_interval: 5s

  # System metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  # PostgreSQL metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Celery metrics (if available)
  - job_name: 'celery'
    static_configs:
      - targets: ['host.docker.internal:8001']  # Celery metrics endpoint
    metrics_path: /metrics
    scrape_interval: 10s

  # RabbitMQ metrics (management plugin)
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['host.docker.internal:15692']  # RabbitMQ Prometheus plugin
    metrics_path: /metrics
    scrape_interval: 10s
